In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# Loading the data
df_orders = pd.read_csv("raw_data/olist_orders_dataset.csv")
df_items = pd.read_csv("raw_data/olist_order_items_dataset.csv")

In [4]:
# Merging the data
master_df = pd.merge(df_orders, df_items, on='order_id', how='inner')

In [5]:
# To see output
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [6]:
# To check the shape of data (Total Rows, Total Columns)
master_df.shape

(112650, 14)

In [7]:
# To describe about the data
master_df.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [8]:
# To check information about data columns and data-type of columns
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   customer_id                    112650 non-null  str
 2   order_status                   112650 non-null  str
 3   order_purchase_timestamp       112650 non-null  str
 4   order_approved_at              112635 non-null  str
 5   order_delivered_carrier_date   111456 non-null  str
 6   order_delivered_customer_date  110196 non-null  str
 7   order_estimated_delivery_date  112650 non-null  str
 8   order_item_id                  112650 non-null  int64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  str
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
dtypes: float64(2), int64(1), str(11)
memory usage: 12.0 MB

In [9]:
# To change or correct the data type of columns like(date to datetime)
cols = ['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'shipping_limit_date']

for c in cols:
    master_df[c] = pd.to_datetime(master_df[c])

In [10]:
# check again the info.
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   customer_id                    112650 non-null  str
 2   order_status                   112650 non-null  str
 3   order_purchase_timestamp       112650 non-null  datetime64[us]
 4   order_approved_at              112635 non-null  str
 5   order_delivered_carrier_date   111456 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  112650 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  int64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
dtypes: datetime64[us](5), float64(2), int64(1), str(6)
memory usage: 12.0 MB

In [11]:
# To check the null values (missing values)
master_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
dtype: int64

In [12]:
# To filter the rows of missing dates.
missing_deliveries = master_df[master_df['order_delivered_customer_date'].isnull()]

# To check the status of missing orders.
print(missing_deliveries['order_status'].value_counts())

order_status
shipped        1185
canceled        535
invoiced        359
processing      357
delivered         8
unavailable       7
approved          3
Name: count, dtype: int64

In [13]:
# To connect with sql database
from sqlalchemy import create_engine

# Creating engine
engine = create_engine("sqlite:///ecommerce_data_analysis.db")

# To save master table into SQL
master_df.to_sql('powerbi_master_sales', con=engine, if_exists='replace', index=False)

print("Data Successfully Saved")

Data Successfully Saved

# Now we will anlayze data by SQL queries

In [14]:
# To display table nice.
from IPython.display import display

# Query 1 :- To show 'Monthly Sales Trend
query_1 = """
Select strftime('%Y', order_purchase_timestamp) AS Year, 
CASE strftime('%m', order_purchase_timestamp)
    WHEN '01' THEN 'Jan'
    WHEN '02' THEN 'Feb'
    WHEN '03' THEN 'Mar'
    WHEN '04' THEN 'Apr'
    WHEN '05' THEN 'May'
    WHEN '06' THEN 'Jun'
    WHEN '07' THEN 'Jul'
    WHEN '08' THEN 'Aug'
    WHEN '09' THEN 'Sep'
    WHEN '10' THEN 'Oct'
    WHEN '11' THEN 'Nov'
    WHEN '12' THEN 'Dec'
END AS Month,
SUM(Price) as Total_Revenue
FROM powerbi_master_sales
GROUP BY Year, Month
ORDER BY Total_Revenue DESC;
"""

display(pd.read_sql(query_1, con=engine))

    Year Month  Total_Revenue
0   2017   Nov     1010271.37
1   2018   Apr      996647.75
2   2018   May      996517.68
3   2018   Mar      983213.44
4   2018   Jan      950030.36
5   2018   Jul      895507.22
6   2018   Jun      865124.31
7   2018   Aug      854686.33
8   2018   Feb      844178.71
9   2017   Dec      743914.17
10  2017   Oct      664219.43
11  2017   Sep      624401.69
12  2017   Aug      573971.68
13  2017   May      506071.14
14  2017   Jul      498031.48
15  2017   Jun      433038.60
16  2017   Mar      374344.30
17  2017   Apr      359927.23
18  2017   Feb      247303.02
19  2017   Jan      120312.87
20  2016   Oct       49507.66
21  2016   Sep         267.36
22  2018   Sep         145.00
23  2016   Dec          10.90

In [15]:
# To check the highest quantity order and value.
query_2 = """
SELECT order_id, COUNT(product_id) AS Total_Qty, SUM(Price) AS Total_Value
FROM powerbi_master_sales
GROUP BY order_id
ORDER BY Total_Qty DESC
LIMIT 5;
"""

display(pd.read_sql(query_2, con=engine))

                           order_id  Total_Qty  Total_Value
0  8272b63d03f5f79c56e9e4120aec44ef         21        31.80
1  ab14fdcfbe524636d65ee38360e22ce8         20      1974.00
2  1b15974a0141d54e36626dca3fdc731a         20      2000.00
3  9ef13efd6949e4573a18964dd1bbe7f5         15       765.00
4  428a2f660dc84138d969ccd69a0ab6d5         15       982.35

In [16]:
master_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value'],
      dtype='str')

In [17]:
# To check the average delivery time in days per delivered order.
query_3 = """
SELECT order_status, ROUND(AVG(julianday(order_delivered_customer_date) - julianday(order_purchase_timestamp)),2) AS Avg_delivery_time_in_days
FROM powerbi_master_sales
WHERE order_status = 'delivered'
GROUP BY order_status
;
"""

display(pd.read_sql(query_3, con=engine))

  order_status  Avg_delivery_time_in_days
0    delivered                      12.47

In [19]:
# To check total_shipping_value ('freight_value) against total_sales_value
query_4 = """
SELECT order_status, SUM(Price) AS Total_Sales, SUM(freight_value) AS Total_Delivery_Charge
FROM powerbi_master_sales
GROUP BY order_status
ORDER BY Total_Delivery_Charge DESC;"""

display(pd.read_sql(query_4, con=engine,))

  order_status  Total_Sales  Total_Delivery_Charge
0    delivered  13221498.11             2198275.64
1      shipped    150727.44               26401.90
2     canceled     95235.27               10650.45
3   processing     60439.22                8954.89
4     invoiced     61526.37                7462.38
5  unavailable      2007.69                 132.80
6     approved       209.60                  31.48